### ISSUE TITLE
Set up Kanban Board

### ISSUE THREAD

**Issue by JohnFTitor** [JohnFTitor/my_recipe_app#15]
## Created Kanban Board

Hello there. We set up a Kanban board based on the requirements of the project and specified tasks for each team member. We are a group of two people.

[You can check the Kanban board here](https://github.com/JohnFTitor/my_recipe_app/projects/1)

<img src="https://media3.giphy.com/media/eSwGh3YK54JKU/giphy.gif"/>

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @JohnFTitor and @Leboroz,

Good job so far!
✔️ Tasks have description
✔️ Kanban columns are well set up
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] I can't seem to find any card that caters to the N+1 query problem task in your board. Kindly add it.

  ![jtfitor](https://user-images.githubusercontent.com/36542986/168652113-e798e6c2-63cb-4829-859c-53390e76a542.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by JohnFTitor** [comment]
Understood.
It's changed now in all tasks that involve creating a view

**Comment by ShoiraTa** [comment]
## **STATUS: APPROVED  🟢 ** 
------
### Hi @Team, 

**Great work on making the changes requested by a previous reviewer 👏🏻** 

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
